dist: trusty
sudo: required

language: java

jdk:
  - oraclejdk8

notifications:
  email: false

services:
  - redis-server

addons:
  postgresql: "9.5"
  apt:
    packages:
      - net-tools
      - libpcre3-dev
      - build-essential

services:
  - redis
  - docker

env:
  global:
    - LUAROCKS=2.4.3
    - OPENSSL=1.1.1a
    - CASSANDRA_BASE=2.2.12
    - CASSANDRA_LATEST=3.9
    - KONG_TEST_DATABASE=cassandra
    - OPENRESTY_BASE=1.15.8.1
    - OPENRESTY_LATEST=1.15.8.1
    - DOWNLOAD_CACHE=$HOME/download-cache
    - INSTALL_CACHE=$HOME/install-cache
    - PLUGIN_NAME=upstream-by-header
    - KONG_TEST_PLUGINS=bundled,$PLUGIN_NAME
    - KONG_PLUGINS=bundled,$PLUGIN_NAME

  matrix:
    - OPENRESTY=$OPENRESTY_BASE
      CASSANDRA=$CASSANDRA_BASE
    - OPENRESTY=$OPENRESTY_LATEST
      CASSANDRA=$CASSANDRA_LATEST

before_install:
  - git clone https://github.com/Kong/kong.git kong-ce
  - source setup_env.sh

install:
  - luarocks make
  - cd kong-ce
  - make dev
  - createuser --createdb kong
  - createdb -U kong kong_tests
  - docker run -d --name httpbin-9004 -p 9004:9000 shashiranjan84/httpbin
  - docker run -d --name httpbin-9005 -p 9005:9000 shashiranjan84/httpbin
  - docker run -d --name httpbin-9006 -p 9006:9000 shashiranjan84/httpbin
  - docker run -d --name httpbin-9007 -p 9007:9000 shashiranjan84/httpbin
  - docker run -d --name httpbin-9008 -p 9008:9000 shashiranjan84/httpbin
  - docker run -d --name httpbin-9009 -p 9009:9000 shashiranjan84/httpbin
  - docker run -d --name httpbin-9010 -p 9010:9000 shashiranjan84/httpbin

script:
  - cd ../
  - luacheck . --exclude-files 'kong-ce/*'
  - cd kong-ce/
  - bin/busted ../spec/

cache:
  apt: true
  pip: true
  directories:
    - $DOWNLOAD_CACHE
    - $INSTALL_CACHE
    - $HOME/.ccm/repository
